version: "3.8"

services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_php
        volumes:
            - .:/var/www/html
        networks:
            - laravel_lab

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - laravel_lab

networks:
    laravel_lab:
        external: true
